package com.mycompany.myapp;


import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Container;
import com.codename1.ui.Toolbar;
import com.codename1.ui.util.UIBuilder;
import java.io.IOException;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    private Object txf;
    private Object tb1;

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
       // Form hi = new Form("Hi World");
       // hi.addComponent(new Label("Hi World"));
       // hi.show();
        UIBuilder ui = new UIBuilder ();
        Container cnt1= ui.createContainer(theme, "GUI 1");
        Form f1 =(Form)cnt1;
        f1.show();
        Label lb1 = (Label) ui.findByName("Lb3", cnt1);
        
        
        Button bt =(Button) ui.findByName("tb1", cnt1);
        bt.addActionListener((e)->{
            tb1.setText("bonjour:"+ txf.getText()); 
                                                    });        
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
